name: pos_nepal
description: POS Nepal.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+15
  font_awesome_flutter: ^8.5.0
  path_provider: ^1.5.1
  #  google_map_polyline: ^0.2.0+1
  #  google_maps_webservice: ^0.0.16
  transparent_image: ^1.0.0
  nice_button: ^0.1.7
  permission: ^0.1.5
  rflutter_alert: ^1.0.3
  flare_flutter: ^1.3.0
  pdf: ^1.3.26
  printing: ^3.0.1
  intl: ^0.16.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - animation/
    - img/
    - img/icons/
    - jsons/
  # fonts:
  #   - family: PressStart2P
  #     fonts:
  #       - asset: third_party/PressStart2P-Regular.ttf
